name: R-CMD-check
on: [push, pull_request]
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest}
          - {os: windows-latest, rtools: '42'}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          rtools-version: ${{ matrix.config.rtools }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::covr
      - uses: r-lib/actions/check-r-package@v2
